#!/bin/bash -e

#This a Slurm script for the stomics SAW pipeline - reference index building

#SBATCH --job-name=stomics-saw
#SBATCH --account=vuw03876
#SBATCH --time=4:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=128GB
#SBATCH --output=/nesi/nobackup/vuw03876/stomics/ref_index%j.out
#SBATCH --error=/nesi/nobackup/vuw03876/stomics/ref_index%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-type=TIME_LIMIT_80
#SBATCH --mail-user=email

cd /nesi/nobackup/vuw03876/stomics

referenceDir=/scale_wlg_nobackup/filesets/nobackup/vuw03876/stomics/Reference/mouse/

export SINGULARITY_BIND=$referenceDir

singularity exec SAW_7.1.sif mapping \
    --runMode genomeGenerate \
    --genomeDir $referenceDir/STAR_SJ100 \
    --genomeFastaFiles $referenceDir/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa \
    --sjdbGTFfile $referenceDir/genes/Mus_musculus.GRCm38.93.gtf \
    --sjdbOverhang 99 \
    --runThreadN 12
